local record Render
    base_present: function(x1: number, y1: number, x2: number, y2: number, x3: number, y3: number, x4: number, y4 : number, rx: number, ry: number, rw: number, rh: number)
    base_present2: function(x1: number, y1: number, x2: number, y2: number, x3: number, y3: number, x4: number, y4 : number, rx: number, ry: number, rw: number, rh: number)
    base_flush: function()
end

return Render
